[package]
name = "vote"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = { workspace = true }
pinocchio-system = { workspace = true }

[dev-dependencies]
litesvm = { workspace = true }
solana-sdk = { workspace = true }
